### ISSUE TITLE
[FIX] 장바구니 화면 스크롤 문제 해결

### ISSUE THREAD

**Issue by oreocube** [woowa-techcamp-2022/android-banchan-07#145]
## Screen Type
- 장바구니

## Description
- 기존 장바구니 화면은 장바구니 목록과 최근 본 목록 두 어댑터를 concat adapter로 구현함
- 각각 데이터를 받아서 넘겨주는 시점의 차이로 인해 스크롤 이슈가 발생하는 것으로 보임
- 두 데이터를 combine 하여 한번에 멀티 뷰타입 리사이클러뷰에 한번에 전달하는 방식으로 변경

## Task
- [x] 최근 본 상품 뷰타입 추가
- [x] 장바구니 목록 유스케이스 수정
- [x] 최근 본 상품 목록 dao flow로 수정
