### ISSUE TITLE
[RELEASE] 1.0.2

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-banchan-07#206]
## Issue
- 버전 1.0.2 릴리즈

## Task
- [x] 다크 모드 대응
- [x] 화면 회전 시 버그 수정
- [x] 뷰 상태 저장 안 되는 버그 수정
- [x] 이미지 placeholder 변경
