### ISSUE TITLE
[FIX] 장바구니에서 최근 본 상품을 선택했을 때 홈 화면으로 팅기는 버그

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-banchan-07#209]
## Issue
- 프래그먼트 Replace 관련

## Description
- 장바구니에서 최근 본 상품을 선택했을 때 홈 화면으로 팅기는 버그

## Task
- [x] 백 스택은 이미 백스택에 존재하더라도 쌓일 수 있도록 수정
- [x] CartFragment는 하나만 생성되도록 popBackStack 활용
- [x] DetailFragment는 계속 BackStack에 쌓일 수 있도록 수정
