### ISSUE TITLE
[FIX] 기획전 화면 수정 사항

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-banchan-07#215]
## Screen Type
- BestFragment

## Description
- 기획전 화면에서 RecyclerView 스크롤, ViewPager 스크롤 중첩 이슈
- 헤더와 아이템 간격 늘리기

## Task
- [x] HorizontalRecyclerView 커스텀 뷰 추가 및 ItemClickListener 추가
- [x] parent RecyclerView는 일반 RecyclerView로 지정
- [x] 리스트 Margin 조정하기
