### ISSUE TITLE
[FIX] 다크모드 수정

### ISSUE THREAD

**Issue by oreocube** [woowa-techcamp-2022/android-banchan-07#217]
## Screen Type
- 공통

## Task
- [ ] 툴바 색상 수정
- [ ] 헤더 배경색 수정
- [ ] 스플래시 스크린 수정
