### ISSUE TITLE
[FEAT] BestFragment

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-banchan-07#23]
## Screen Type
- BestFragment

## Description
- BestFragment 구현하기

## Task
- [x] 리사이클러뷰 어댑터 구현
- [x] Item Spacing 넣기
- [x] 서버에서 데이터 불러오기
