### ISSUE TITLE
[FEAT] MainDishFragment

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-banchan-07#29]
## Screen Type
- MainDishFragment

## Description
- 든든한 메인요리 화면 구현

## Task
- [x] 리스트 형식 리사이클러뷰 어댑터 구현
- [x] 할인율, 원가 데이터가 0원일 때 뷰에서 숨기기
- [x] 갤러리 형식, 리스트 형식에 따라 다르게 보여주기
- [x] 옵션에 따라 정렬방식 바꾸기
