### ISSUE TITLE
[FEAT] DetailFragment

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-banchan-07#37]
## Screen Type
- 음식 자세히 보기 화면

## Description
- 음식 자세히 보기 화면 구현하기

## Task
- [x] HomeFragment에서 타 화면으로 이동 후 뒤로가기 버튼 클릭 시 팅김 오류 수정하기
- [x] HomeFragment에서 DetailFragment로 이동
- [x] 자세히 보기 뷰 구현하기
- [x] 서버에서 디테일 데이터 가져오기
- [x] 주문하기 기능 추가
- [x] Detail 들어갈 때 Recently에 값 넣기
- [x] 돈 계산하기
