### ISSUE TITLE
[FEAT] 장바구니 바텀시트 데이터 연결

### ISSUE THREAD

**Issue by oreocube** [woowa-techcamp-2022/android-banchan-07#38]
## Screen Type
- 장바구니 바텀시트

## Description
- 장바구니 바텀시트에 데이터를 연결하고 이벤트를 처리한다.

## Task
- [x] 전달받은 음식 정보 표시
- [x] 수량 이벤트 처리
- [x] 카트 담기 이벤트 처리
