### ISSUE TITLE
[UI] 장바구니 화면 레이아웃

### ISSUE THREAD

**Issue by oreocube** [woowa-techcamp-2022/android-banchan-07#42]
## Screen Type
- 장바구니

## Description
- 장바구니 화면 레이아웃 구현

## Task
- [x] 카트 아이템 영역 레이아웃
- [x] 금액 합계 영역 레이아웃
- [x] 최근 본 아이템 영역 레이아웃
