### ISSUE TITLE
[FIX] CartFragment

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-banchan-07#61]
## Screen Type
- CartFragment

## Description
- 장바구니 화면 수정 사항

## Task
- [x] 최근 본 상품 리스트 Space 수정
- [x] 백 버튼 클릭 시 뒤 페이지로 이동하기
- [x] 프래그먼트별 툴바 변경
- [x] 장바구니 추가 시 장바구니 화면 이동 버튼 클릭하면 이동하기
