### ISSUE TITLE
[FIX] 음식 자세히 보기 화면

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-banchan-07#71]
## Screen Type
- DetailFragment

## Description
- 음식 자세히 보기 화면 수정

## Task
- [x] 음식 주문 시 thumbnail을 thumbImage의 0번 index 보내기
- [x] 다른 화면 이동 후 종료 시점에 어댑터 초기화하기(lazy 사용하지 않기)
- [ ] tabLayout Item Ripple 제거하기
