### ISSUE TITLE
[REFECTOR] RecentlyAdapter 리팩토링 및 클릭 시 바텀 시트, 화면 이동 구현

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-banchan-07#92]
## Screen Type
- CartFragment, RecentlyViewedFragment

## Description
-  RecentlyAdapter 리팩토링 및 클릭 시 바텀 시트, 화면 이동 구현

## Task
- [x] RecentlyAdapter ViewHolder Grid/Horizontal Sealed Class로 분리
- [x] Recently 아이템 클릭 시 화면 이동
- [x] 장바구니 버튼 클릭 시 바텀 시트 띄우기
