### ISSUE TITLE
[FIX] 홈 화면 수정 사항

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-banchan-07#97]
## Screen Type
- HomeFragment

## Description
- 홈 화면 수정 사항

## Task
- [x] Binding 변수를 nullable하도록 수정 및 onDestroyView 호출 시 null로 초기화
- [x] 리스트 아이템 헤더부분 Space 수정
- [x] 기획전 아이템 Space 없어지는 버그 수정
- [x] onDestroy 시 필요없는 초기화 코드 제거
